
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import xyztecnologia.model.Aluno;
import xyztecnologia.model.Curso;
import xyztecnologia.model.Professor;
import xyztecnologia.view.AlunoView;
import xyztecnologia.view.CursoView;
import xyztecnologia.view.ProfessorView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dawittralph
 */
public class XYZTecnologiaMain extends javax.swing.JFrame {

    /**
     * Creates new form XYZTecnologiaMain
     */
    
    //Criação de um objeto pr do tipo Curso.
    CursoView cr = null;
    Curso curso[] = new Curso[1];
    
    //Criação de um objeto pr do tipo Professor.
    ProfessorView pr = null;
    Professor professor[] = new Professor[1];
    
    //Criação de um objeto al do tipo Aluno.
    AlunoView al = null;
    Aluno aluno[] = new Aluno[2];
    
    
    public XYZTecnologiaMain() {
        initComponents();
        pnlCursos.setVisible(false);
        pnlProfessores.setVisible(false);
        pnlAlunos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanner = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();
        pnlProfessores = new javax.swing.JPanel();
        lblProfessores = new javax.swing.JLabel();
        btnCadastraProfessor = new javax.swing.JButton();
        btnExibirProfessor = new javax.swing.JButton();
        pnlAlunos = new javax.swing.JPanel();
        lblAlunos = new javax.swing.JLabel();
        btnCadastrarAluno = new javax.swing.JButton();
        btnExibirAluno = new javax.swing.JButton();
        pnlCursos = new javax.swing.JPanel();
        lblCursos = new javax.swing.JLabel();
        btnCadastrarCurso = new javax.swing.JButton();
        btnExibirCurso = new javax.swing.JButton();
        btnCustoCurso = new javax.swing.JButton();
        mmPrincipal = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mniCurso = new javax.swing.JMenuItem();
        mniProfessor = new javax.swing.JMenuItem();
        mniAluno = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle Educacional");
        setName("pnlPrincipal"); // NOI18N

        pnlBanner.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanner.setName("pnlBanner"); // NOI18N

        lblBanner.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblBanner.setForeground(new java.awt.Color(0, 0, 0));
        lblBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanner.setText("XYZ - Tecnologia");
        lblBanner.setAlignmentY(0.0F);
        lblBanner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBanner.setName("lblBanner"); // NOI18N

        javax.swing.GroupLayout pnlBannerLayout = new javax.swing.GroupLayout(pnlBanner);
        pnlBanner.setLayout(pnlBannerLayout);
        pnlBannerLayout.setHorizontalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE))
        );
        pnlBannerLayout.setVerticalGroup(
            pnlBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBannerLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblBanner)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlProfessores.setBackground(java.awt.Color.white);
        pnlProfessores.setName("pnlProfessores"); // NOI18N

        lblProfessores.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        lblProfessores.setText("Cadastro de Professores");

        btnCadastraProfessor.setText("Cadastrar");
        btnCadastraProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraProfessorActionPerformed(evt);
            }
        });

        btnExibirProfessor.setText("Exibir");
        btnExibirProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProfessoresLayout = new javax.swing.GroupLayout(pnlProfessores);
        pnlProfessores.setLayout(pnlProfessoresLayout);
        pnlProfessoresLayout.setHorizontalGroup(
            pnlProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfessoresLayout.createSequentialGroup()
                .addGroup(pnlProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfessores)
                    .addGroup(pnlProfessoresLayout.createSequentialGroup()
                        .addComponent(btnCadastraProfessor)
                        .addGap(18, 18, 18)
                        .addComponent(btnExibirProfessor)))
                .addGap(0, 496, Short.MAX_VALUE))
        );
        pnlProfessoresLayout.setVerticalGroup(
            pnlProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfessoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfessores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(pnlProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastraProfessor)
                    .addComponent(btnExibirProfessor)))
        );

        pnlAlunos.setBackground(java.awt.Color.white);
        pnlAlunos.setName("pnlProfessores"); // NOI18N
        pnlAlunos.setPreferredSize(new java.awt.Dimension(212, 119));

        lblAlunos.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        lblAlunos.setText("Cadastro de Alunos");

        btnCadastrarAluno.setText("Cadastrar");
        btnCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAlunoActionPerformed(evt);
            }
        });

        btnExibirAluno.setText("Exibir");
        btnExibirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAlunosLayout = new javax.swing.GroupLayout(pnlAlunos);
        pnlAlunos.setLayout(pnlAlunosLayout);
        pnlAlunosLayout.setHorizontalGroup(
            pnlAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlunosLayout.createSequentialGroup()
                .addGroup(pnlAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlunos)
                    .addGroup(pnlAlunosLayout.createSequentialGroup()
                        .addComponent(btnCadastrarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(btnExibirAluno)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAlunosLayout.setVerticalGroup(
            pnlAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pnlAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarAluno)
                    .addComponent(btnExibirAluno)))
        );

        pnlCursos.setBackground(java.awt.Color.white);
        pnlCursos.setName("pnlProfessores"); // NOI18N
        pnlCursos.setPreferredSize(new java.awt.Dimension(212, 119));

        lblCursos.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        lblCursos.setText("Cadastro de Cursos");

        btnCadastrarCurso.setText("Cadastrar");
        btnCadastrarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCursoActionPerformed(evt);
            }
        });

        btnExibirCurso.setText("Exibir");
        btnExibirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirCursoActionPerformed(evt);
            }
        });

        btnCustoCurso.setText("Custo do Curso");
        btnCustoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustoCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCursosLayout = new javax.swing.GroupLayout(pnlCursos);
        pnlCursos.setLayout(pnlCursosLayout);
        pnlCursosLayout.setHorizontalGroup(
            pnlCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursosLayout.createSequentialGroup()
                .addGroup(pnlCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCursos)
                    .addGroup(pnlCursosLayout.createSequentialGroup()
                        .addComponent(btnCadastrarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btnExibirCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btnCustoCurso)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCursosLayout.setVerticalGroup(
            pnlCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(pnlCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarCurso)
                    .addComponent(btnExibirCurso)
                    .addComponent(btnCustoCurso)))
        );

        mmPrincipal.setName("mnbPrincipal"); // NOI18N

        mnArquivo.setText("Arquivo");

        mniCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mniCurso.setText("Curso");
        mniCurso.setName("mniCurso"); // NOI18N
        mniCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCursoActionPerformed(evt);
            }
        });
        mnArquivo.add(mniCurso);

        mniProfessor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        mniProfessor.setLabel("Professor");
        mniProfessor.setName("mniProfessor"); // NOI18N
        mniProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProfessorActionPerformed(evt);
            }
        });
        mnArquivo.add(mniProfessor);

        mniAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        mniAluno.setLabel("Aluno");
        mniAluno.setName("mniAluno"); // NOI18N
        mniAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlunoActionPerformed(evt);
            }
        });
        mnArquivo.add(mniAluno);

        mmPrincipal.add(mnArquivo);

        mnSair.setText("Sair");
        mmPrincipal.add(mnSair);

        setJMenuBar(mmPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addComponent(pnlCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProfessorActionPerformed
        // TODO add your handling code here:
        pnlCursos.setVisible(false);
        pnlProfessores.setVisible(true);
        pnlAlunos.setVisible(false);
    }//GEN-LAST:event_mniProfessorActionPerformed

    private void mniCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCursoActionPerformed
        // TODO add your handling code here:
        pnlCursos.setVisible(true);
        pnlProfessores.setVisible(false);
        pnlAlunos.setVisible(false);
    }//GEN-LAST:event_mniCursoActionPerformed

    private void mniAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlunoActionPerformed
        // TODO add your handling code here:
        pnlCursos.setVisible(false);
        pnlProfessores.setVisible(false);
        pnlAlunos.setVisible(true);
    }//GEN-LAST:event_mniAlunoActionPerformed

    private void btnCadastraProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraProfessorActionPerformed
        // TODO add your handling code here:
        pr = new ProfessorView();
        pr.cadastrarProfessor();
    }//GEN-LAST:event_btnCadastraProfessorActionPerformed

    private void btnExibirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirAlunoActionPerformed
        // TODO add your handling code here:
        al = new AlunoView();
        al.listarAluno();
    }//GEN-LAST:event_btnExibirAlunoActionPerformed

    private void btnCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAlunoActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < aluno.length; i++) {
            al = new AlunoView();
            al.cadastrarAluno();
        }
    }//GEN-LAST:event_btnCadastrarAlunoActionPerformed

    private void btnExibirProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirProfessorActionPerformed
        // TODO add your handling code here:
        pr = new ProfessorView();
        pr.listarProfessor();
    }//GEN-LAST:event_btnExibirProfessorActionPerformed

    private void btnCadastrarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCursoActionPerformed
        // TODO add your handling code here:
        cr = new CursoView();
        cr.cadastrarCurso();
    }//GEN-LAST:event_btnCadastrarCursoActionPerformed

    private void btnExibirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirCursoActionPerformed
        // TODO add your handling code here:
        cr = new CursoView();
        cr.listarCurso();
    }//GEN-LAST:event_btnExibirCursoActionPerformed

    private void btnCustoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustoCursoActionPerformed
        // TODO add your handling code here:
        try {
            cr = new CursoView();
            pr = new ProfessorView();
            JOptionPane.showMessageDialog(null, "A quantidade mínima de alunos é de: " + Math.round(pr.retornaSalBruto()/ cr.retornaValor()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro na captura do valor do curso e/ou do salário bruto do professor!");
        }

    }//GEN-LAST:event_btnCustoCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XYZTecnologiaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XYZTecnologiaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XYZTecnologiaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XYZTecnologiaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XYZTecnologiaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastraProfessor;
    private javax.swing.JButton btnCadastrarAluno;
    private javax.swing.JButton btnCadastrarCurso;
    private javax.swing.JButton btnCustoCurso;
    private javax.swing.JButton btnExibirAluno;
    private javax.swing.JButton btnExibirCurso;
    private javax.swing.JButton btnExibirProfessor;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblCursos;
    private javax.swing.JLabel lblProfessores;
    private javax.swing.JMenuBar mmPrincipal;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnSair;
    private javax.swing.JMenuItem mniAluno;
    private javax.swing.JMenuItem mniCurso;
    private javax.swing.JMenuItem mniProfessor;
    private javax.swing.JPanel pnlAlunos;
    private javax.swing.JPanel pnlBanner;
    private javax.swing.JPanel pnlCursos;
    private javax.swing.JPanel pnlProfessores;
    // End of variables declaration//GEN-END:variables
}
